pipeline:
  name: Build testgo
  identifier: Build_testgo_1733900976636
  projectIdentifier: testgoharnessci
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: false
          execution:
            steps:
              - step:
                  type: Run
                  name: Echo Welcome Message
                  identifier: Echo_Welcome_Message
                  spec:
                    connectorRef: account.harnessImage
                    image: harness/drone-git:1.6.2
                    shell: Sh
                    command: |-
                      echo "Welcome to Harness CI"
                      sleep 1000
          platform:
            os: MacOS
            arch: Arm64
          runtime:
            type: Docker
            spec: {}
          caching:
            enabled: false
            paths: []
          buildIntelligence:
            enabled: false
        description: ""
